#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=25

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="/opt/anki-beeminder"
STATE_DIR="/var/lib/anki-beeminder"
SYNC_BASE="$STATE_DIR/sync"
COLLECTION_PATH="$SYNC_BASE/collection.anki2"
SYSTEM_CONFIG_DIR="/etc/anki-beeminder"
SYSTEMD_DIR="/etc/systemd/system"
SETUP_STATE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/anki-beeminder"
mkdir -p "$SETUP_STATE_DIR"
chmod 700 "$SETUP_STATE_DIR"
ENV_FILE="$SETUP_STATE_DIR/setup.env"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

die() {
  printf '%sERROR: %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

ask_default() {
  local key="$1" prompt="$2" default="$3"
  ask "$key" "$prompt"
  if [[ -z "${!key}" ]]; then
    printf -v "$key" '%s' "$default"
  fi
}

require_value() {
  [[ -n "$2" ]] || die "$1 is required"
}

install_systemd_env() {
  local destination="$1"
  shift
  local temporary_file key value
  temporary_file=$(mktemp)
  while (( $# >= 2 )); do
    key="$1"
    value="$2"
    printf '%s=%q\n' "$key" "$value" >> "$temporary_file"
    shift 2
  done
  sudo install -o root -g anki -m 0640 "$temporary_file" "$destination"
  rm -f "$temporary_file"
}

install_app_files() {
  sudo install -d -o anki -g anki -m 0755 "$APP_DIR" "$APP_DIR/scripts"
  sudo install -o root -g root -m 0644 "$REPO_ROOT/metrics.py" "$APP_DIR/metrics.py"
  sudo install -o root -g root -m 0644 "$REPO_ROOT/requirements-worker.txt" "$APP_DIR/requirements-worker.txt"
  sudo install -o root -g root -m 0644 "$REPO_ROOT/scripts/__init__.py" "$APP_DIR/scripts/__init__.py"
  sudo install -o root -g root -m 0644 "$REPO_ROOT/scripts/daily_beeminder_sync.py" "$APP_DIR/scripts/daily_beeminder_sync.py"
  sudo install -o root -g root -m 0644 "$REPO_ROOT/deploy/linux/anki-sync-server.service" "$SYSTEMD_DIR/anki-sync-server.service"
  sudo install -o root -g root -m 0644 "$REPO_ROOT/deploy/linux/anki-beeminder.service" "$SYSTEMD_DIR/anki-beeminder.service"
  sudo install -o root -g root -m 0644 "$REPO_ROOT/deploy/linux/anki-beeminder.timer" "$SYSTEMD_DIR/anki-beeminder.timer"
}

banner "Linux Anki sync + Beeminder setup"

stage "Back up and prepare the current collection" 5
say "This setup creates a new local sync server. It does not copy or overwrite your existing AnkiWeb collection automatically."
step "In desktop Anki, sync from AnkiWeb so the desktop collection is current."
step "Create a fresh desktop backup/export before changing any sync settings."
pause "When the backup and final AnkiWeb sync are complete, press Enter."
confirm "Have you made the backup and confirmed desktop Anki is current?" || die "stopped before the migration safety checkpoint"

stage "Choose the local sync endpoint" 3
say "Use 0.0.0.0 only as the Linux bind address; clients should use the laptop's LAN/VPN IP or DNS name."
ask_default SYNC_HOST "Linux bind host [0.0.0.0]:" "0.0.0.0"
ask_default SYNC_PORT "Linux sync port [8080]:" "8080"
DEFAULT_CLIENT_HOST="$(hostname -I 2>/dev/null | awk '{print $1}')"
DEFAULT_CLIENT_HOST="${DEFAULT_CLIENT_HOST:-127.0.0.1}"
ask_default SYNC_CLIENT_HOST "Client-visible Linux host [$DEFAULT_CLIENT_HOST]:" "$DEFAULT_CLIENT_HOST"
write_env SYNC_HOST "$SYNC_HOST"
write_env SYNC_PORT "$SYNC_PORT"
write_env SYNC_CLIENT_HOST "$SYNC_CLIENT_HOST"

stage "Create local sync credentials" 3
say "These credentials are only for this self-hosted server. Do not reuse your AnkiWeb password."
ask SYNC_USERNAME "Local sync username:"
ask_secret SYNC_PASSWORD "Local sync password:"
require_value "SYNC_USERNAME" "$SYNC_USERNAME"
require_value "SYNC_PASSWORD" "$SYNC_PASSWORD"
write_env SYNC_USERNAME "$SYNC_USERNAME"
write_env SYNC_PASSWORD "$SYNC_PASSWORD"

stage "Configure the Beeminder worker" 3
ask BEEMINDER_USER "Beeminder username:"
ask_secret BEEMINDER_TOKEN "Beeminder API token:"
ask BEEMINDER_GOAL "Beeminder goal slug:"
ask ANKI_DECK_FILTER "Deck filter (blank for all decks):"
ask_default ANKI_TIMEZONE "Timezone [Europe/Ljubljana]:" "Europe/Ljubljana"
require_value "BEEMINDER_USER" "$BEEMINDER_USER"
require_value "BEEMINDER_TOKEN" "$BEEMINDER_TOKEN"
require_value "BEEMINDER_GOAL" "$BEEMINDER_GOAL"
write_env BEEMINDER_USER "$BEEMINDER_USER"
write_env BEEMINDER_TOKEN "$BEEMINDER_TOKEN"
write_env BEEMINDER_GOAL "$BEEMINDER_GOAL"
write_env ANKI_DECK_FILTER "$ANKI_DECK_FILTER"
write_env ANKI_TIMEZONE "$ANKI_TIMEZONE"

stage "Install and start Linux services" 7
say "The commands below install the official Anki Python package, create an unprivileged service account, and configure systemd."
step "Installing prerequisites and creating /opt/anki-beeminder and /var/lib/anki-beeminder."
sudo apt-get update
sudo apt-get install --yes ca-certificates python3 python3-venv
if ! getent group anki >/dev/null 2>&1; then
  sudo groupadd --system anki
fi
if ! getent passwd anki >/dev/null 2>&1; then
  sudo useradd --system --gid anki --home-dir "$STATE_DIR" --shell /usr/sbin/nologin anki
fi
sudo install -d -o anki -g anki -m 0750 "$STATE_DIR" "$SYNC_BASE"
sudo install -d -o root -g anki -m 0750 "$SYSTEM_CONFIG_DIR"
install_app_files
if [[ ! -x "$APP_DIR/venv/bin/python" ]]; then
  sudo -u anki python3 -m venv "$APP_DIR/venv"
fi
sudo -u anki "$APP_DIR/venv/bin/python" -m pip install --disable-pip-version-check -r "$APP_DIR/requirements-worker.txt"
install_systemd_env "$SYSTEM_CONFIG_DIR/anki-sync-server.env" \
  SYNC_USER1 "${SYNC_USERNAME}:${SYNC_PASSWORD}" \
  SYNC_BASE "$SYNC_BASE" \
  SYNC_HOST "$SYNC_HOST" \
  SYNC_PORT "$SYNC_PORT"
install_systemd_env "$SYSTEM_CONFIG_DIR/anki-beeminder.env" \
  ANKI_COLLECTION_PATH "$COLLECTION_PATH" \
  ANKI_DECK_FILTER "$ANKI_DECK_FILTER" \
  ANKI_TIMEZONE "$ANKI_TIMEZONE" \
  BEEMINDER_USER "$BEEMINDER_USER" \
  BEEMINDER_TOKEN "$BEEMINDER_TOKEN" \
  BEEMINDER_GOAL "$BEEMINDER_GOAL"
sudo systemctl daemon-reload
sudo systemctl enable --now anki-sync-server.service
sudo systemctl enable --now anki-beeminder.timer
sudo systemctl is-active --quiet anki-sync-server.service || {
  sudo systemctl status anki-sync-server.service --no-pager || true
  die "the Anki sync server did not start; inspect journalctl -u anki-sync-server"
}

stage "Point Anki clients at Linux" 4
SYNC_URL="http://${SYNC_CLIENT_HOST}:${SYNC_PORT}/"
say "The server is running at $SYNC_URL"
step "In desktop Anki's syncing preferences, choose the self-hosted sync server and enter $SYNC_URL."
step "Use the local sync username/password from the previous stage."
step "On the first sync, choose Upload to server so the backed-up current desktop collection becomes the server copy."
step "After desktop sync succeeds, configure AnkiMobile with the same URL and credentials, then sync it."
warn "If the first-sync direction is not what you expect, stop and restore the backup; do not guess."
pause "Complete the desktop upload and mobile sync, then press Enter."
confirm "Has the current desktop collection been uploaded to the Linux server and checked on mobile?" || die "stopped before confirming client cutover"
sudo test -f "$COLLECTION_PATH" || die "the server collection was not found at $COLLECTION_PATH"

stage "Run a dry-run and hand off" 3
say "This dry-run reads a SQLite snapshot and does not call Beeminder."
if confirm "Run the local worker dry-run now?"; then
  sudo -u anki env \
    "ANKI_COLLECTION_PATH=$COLLECTION_PATH" \
    "ANKI_DECK_FILTER=$ANKI_DECK_FILTER" \
    "ANKI_TIMEZONE=$ANKI_TIMEZONE" \
    "BEEMINDER_USER=$BEEMINDER_USER" \
    "BEEMINDER_TOKEN=$BEEMINDER_TOKEN" \
    "BEEMINDER_GOAL=$BEEMINDER_GOAL" \
    "$APP_DIR/venv/bin/python" -m scripts.daily_beeminder_sync --dry-run
fi
say "The real worker will run at 21:05 host local time."
say "Manual commands:"
note "  sudo systemctl start anki-beeminder.service"
note "  sudo systemctl status anki-sync-server.service --no-pager"
note "  sudo systemctl list-timers anki-beeminder.timer"
note "  sudo journalctl -u anki-sync-server -u anki-beeminder --since today"

finish
